# Builds and publishes the documentation website to gh-pages branch
name: Build docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build static site content using DocFX
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
         args: docs/docfx.json
          
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true
